// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUQuMQnwUhlwjdKEwwEPPEOpyvC3h8uc',
    appId: '1:340429227480:web:166f8aba06bdfc9ebb1ead',
    messagingSenderId: '340429227480',
    projectId: 'p10-yaahowu',
    authDomain: 'p10-yaahowu.firebaseapp.com',
    storageBucket: 'p10-yaahowu.firebasestorage.app',
    measurementId: 'G-01VP1HSX3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ0POwg4so4wWvKSwM9GOn600qO8YWHOo',
    appId: '1:340429227480:android:832718c75eb1534bbb1ead',
    messagingSenderId: '340429227480',
    projectId: 'p10-yaahowu',
    storageBucket: 'p10-yaahowu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnFSpFXc6W-JpNWPeBsTaKCrW85MjGSCI',
    appId: '1:340429227480:ios:58d45525614ef709bb1ead',
    messagingSenderId: '340429227480',
    projectId: 'p10-yaahowu',
    storageBucket: 'p10-yaahowu.firebasestorage.app',
    iosBundleId: 'com.example.p10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnFSpFXc6W-JpNWPeBsTaKCrW85MjGSCI',
    appId: '1:340429227480:ios:58d45525614ef709bb1ead',
    messagingSenderId: '340429227480',
    projectId: 'p10-yaahowu',
    storageBucket: 'p10-yaahowu.firebasestorage.app',
    iosBundleId: 'com.example.p10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvUQuMQnwUhlwjdKEwwEPPEOpyvC3h8uc',
    appId: '1:340429227480:web:7de7e748452fab09bb1ead',
    messagingSenderId: '340429227480',
    projectId: 'p10-yaahowu',
    authDomain: 'p10-yaahowu.firebaseapp.com',
    storageBucket: 'p10-yaahowu.firebasestorage.app',
    measurementId: 'G-8B0QZ0Z1TQ',
  );
}
